In [1]:
import numpy as np 
import pandas as pd
import glob

In [2]:
from pycaret.classification import *

In [3]:
my_data = pd.read_csv("Classifi_all_data_beforeFI.csv")
my_data.head()

,VV,VH,VV-VH,Entropy,Anisotropy,Alpha,GLCM PC1,GLCM PC2,GLCM PC3,GLCM PC4,...,GLCM PC6,DEM,PC1,PC2,PC3,PC4,PC5,PC6,ClassID,Class_name
0,-19.127264,-26.148289,7.021025,0.802243,0.511247,24.109398,-11.121046,2.120520,-1.187986,0.305749,...,0.766538,46,1.045,0.114,0.089072,0.028547,0.028547,0.008142,1,ASK
1,-17.905613,-27.497355,9.591742,0.783197,0.534009,24.449989,-11.905989,-0.035668,0.034768,0.406617,...,-0.152389,54,1.049,0.117,0.090146,0.029851,0.029851,0.008729,1,ASK
2,-15.280186,-22.360802,7.080616,0.771204,0.547740,23.534164,-7.164552,-7.279618,0.445399,1.520445,...,-1.244990,54,1.027,0.126,0.087076,0.028418,0.028418,0.005288,1,ASK
3,-14.594241,-20.822491,6.228250,0.814251,0.496232,24.446283,-5.439240,0.077479,-1.435103,-0.307729,...,-0.860380,59,1.005,0.115,0.085156,0.031047,0.031047,0.008023,1,ASK
4,-14.800154,-19.735399,4.935246,0.846771,0.452534,28.770714,-4.033033,0.462254,2.218574,-0.027918,...,-0.528220,53,1.020,0.122,0.082730,0.032016,0.032016,0.004915,1,ASK

In [4]:
my_data.drop(['ClassID'], axis = 1, inplace = True)

In [5]:
my_data.head()

,VV,VH,VV-VH,Entropy,Anisotropy,Alpha,GLCM PC1,GLCM PC2,GLCM PC3,GLCM PC4,GLCM PC5,GLCM PC6,DEM,PC1,PC2,PC3,PC4,PC5,PC6,Class_name
0,-19.127264,-26.148289,7.021025,0.802243,0.511247,24.109398,-11.121046,2.120520,-1.187986,0.305749,-0.217070,0.766538,46,1.045,0.114,0.089072,0.028547,0.028547,0.008142,ASK
1,-17.905613,-27.497355,9.591742,0.783197,0.534009,24.449989,-11.905989,-0.035668,0.034768,0.406617,-0.557473,-0.152389,54,1.049,0.117,0.090146,0.029851,0.029851,0.008729,ASK
2,-15.280186,-22.360802,7.080616,0.771204,0.547740,23.534164,-7.164552,-7.279618,0.445399,1.520445,-0.423039,-1.244990,54,1.027,0.126,0.087076,0.028418,0.028418,0.005288,ASK
3,-14.594241,-20.822491,6.228250,0.814251,0.496232,24.446283,-5.439240,0.077479,-1.435103,-0.307729,-0.324791,-0.860380,59,1.005,0.115,0.085156,0.031047,0.031047,0.008023,ASK
4,-14.800154,-19.735399,4.935246,0.846771,0.452534,28.770714,-4.033033,0.462254,2.218574,-0.027918,-0.247315,-0.528220,53,1.020,0.122,0.082730,0.032016,0.032016,0.004915,ASK

In [6]:
cls_all = setup(my_data, target = 'Class_name',train_size = 0.7,session_id=123,log_experiment=True, experiment_name='cls_all')

2023/01/20 11:50:16 INFO mlflow.tracking.fluent: Experiment with name 'cls_all' does not exist. Creating a new experiment.
2023/01/20 11:50:16 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet

In [7]:
best_model = compare_models()

Processing:   0%|          | 0/65 [00:00<?, ?it/s]