In [1]:
import numpy as np 
import pandas as pd
import glob

In [2]:
from pycaret.classification import *

In [3]:
my_data = pd.read_csv("Classifi_all_data_afterFI.csv")
my_data.head()

,VV,Entropy,Anisotropy,GLCM PC1,DEM,PC1,PC2,PC3,PC4,PC6,ClassID,Class_name
0,-19.127264,0.802243,0.511247,-11.121046,46,1.045,0.114,0.089072,0.028547,0.008142,1,ASK
1,-17.905613,0.783197,0.534009,-11.905989,54,1.049,0.117,0.090146,0.029851,0.008729,1,ASK
2,-15.280186,0.771204,0.547740,-7.164552,54,1.027,0.126,0.087076,0.028418,0.005288,1,ASK
3,-14.594241,0.814251,0.496232,-5.439240,59,1.005,0.115,0.085156,0.031047,0.008023,1,ASK
4,-14.800154,0.846771,0.452534,-4.033033,53,1.020,0.122,0.082730,0.032016,0.004915,1,ASK

In [4]:
my_data.drop(['ClassID'], axis = 1, inplace = True)

In [6]:
my_data.head()

,VV,Entropy,Anisotropy,GLCM PC1,DEM,PC1,PC2,PC3,PC4,PC6,Class_name
0,-19.127264,0.802243,0.511247,-11.121046,46,1.045,0.114,0.089072,0.028547,0.008142,ASK
1,-17.905613,0.783197,0.534009,-11.905989,54,1.049,0.117,0.090146,0.029851,0.008729,ASK
2,-15.280186,0.771204,0.547740,-7.164552,54,1.027,0.126,0.087076,0.028418,0.005288,ASK
3,-14.594241,0.814251,0.496232,-5.439240,59,1.005,0.115,0.085156,0.031047,0.008023,ASK
4,-14.800154,0.846771,0.452534,-4.033033,53,1.020,0.122,0.082730,0.032016,0.004915,ASK

In [7]:
cls_all_fi = setup(my_data, target = 'Class_name',train_size = 0.7,session_id=123,log_experiment=True, experiment_name='cls_all_fi')

2023/01/20 11:45:08 INFO mlflow.tracking.fluent: Experiment with name 'cls_all_fi' does not exist. Creating a new experiment.
2023/01/20 11:45:08 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet

In [8]:
best_model = compare_models()

Processing:   0%|          | 0/65 [00:00<?, ?it/s]