In [1]:
import numpy as np 
import pandas as pd
import glob

In [2]:
from pycaret.classification import *

In [3]:
my_data = pd.read_csv("Classifi_glcm_data.csv")
my_data.head()

,GLCM PC1,GLCM PC2,GLCM PC3,GLCM PC4,GLCM PC5,GLCM PC6,ClassID,Class_name
0,-11.121046,2.120520,-1.187986,0.305749,-0.217070,0.766538,1,ASK
1,-11.905989,-0.035668,0.034768,0.406617,-0.557473,-0.152389,1,ASK
2,-7.164552,-7.279618,0.445399,1.520445,-0.423039,-1.244990,1,ASK
3,-5.439240,0.077479,-1.435103,-0.307729,-0.324791,-0.860380,1,ASK
4,-4.033033,0.462254,2.218574,-0.027918,-0.247315,-0.528220,1,ASK

In [4]:
my_data.drop(['ClassID'], axis = 1, inplace = True)

In [5]:
my_data.head()

    GLCM PC1  GLCM PC2  GLCM PC3  GLCM PC4  GLCM PC5  GLCM PC6 Class_name
0 -11.121046  2.120520 -1.187986  0.305749 -0.217070  0.766538        ASK
1 -11.905989 -0.035668  0.034768  0.406617 -0.557473 -0.152389        ASK
2  -7.164552 -7.279618  0.445399  1.520445 -0.423039 -1.244990        ASK
3  -5.439240  0.077479 -1.435103 -0.307729 -0.324791 -0.860380        ASK
4  -4.033033  0.462254  2.218574 -0.027918 -0.247315 -0.528220        ASK

In [6]:
cls_glcm = setup(my_data, target = 'Class_name',train_size = 0.7,session_id=123,log_experiment=True, experiment_name='cls_glcm')

2023/01/20 12:02:17 INFO mlflow.tracking.fluent: Experiment with name 'cls_glcm' does not exist. Creating a new experiment.
2023/01/20 12:02:17 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet

In [7]:
best_model = compare_models()

Processing:   0%|          | 0/65 [00:00<?, ?it/s]